name = "fhir"
version = "0.1.0"

description = "Type-safe FHIR resources and client"
licences = ["MIT"]
repository = { type = "github", user = "PotatoEMR", repo = "gleam-fhir" }

links = [
  { title = "Todo Issues", href = "https://github.com/PotatoEMR/gleam-fhir/issues/" },
]

[documentation]
pages = [
  { title = "Release Notes", path = "releasenotes.html", source = "./ReleaseNotes.md" },
  { title = " ", path = "#", source = "" },
  { title = "Gleam FHIR Resources", path = "resources.html", source = "./docs/resources/01-fhirresources.md" },
  { title = "• Primitive Type", path = "resources/primitivetype.html", source = "./docs/resources/02-primitivetype.md" },
  { title = "• Complex Type", path = "resources/complextype.html", source = "./docs/resources/03-complextype.md" },
  { title = "• BackboneElement", path = "resources/backboneelement.html", source = "./docs/resources/04-backboneelement.md" },
  { title = "• Cardinality", path = "resources/cardinality.html", source = "./docs/resources/05-cardinality.md" },
  { title = "• Choice Element", path = "resources/choiceelement.html", source = "./docs/resources/06-choiceelement.md" },
  { title = "• id vs Identifier", path = "resources/id-vs-identifier.html", source = "./docs/resources/07-idvsidentifier.md" },
  { title = "• Reference", path = "resources/reference.html", source = "./docs/resources/08-reference.md" },
  { title = "• code", path = "resources/code.html", source = "./docs/resources/09-code.md" },
  { title = "• Coding", path = "resources/coding.html", source = "./docs/resources/10-coding.md" },
  { title = "• CodeableConcept", path = "resources/codeableconcept.html", source = "./docs/resources/11-codeableconcept.md" },
  { title = "• CodeableReference", path = "resources/codeablereference.html", source = "./docs/resources/12-codeablereference.md" },
  { title = "• Extension", path = "resources/extension.html", source = "./docs/resources/12-extension.md" },
  { title = "• Bundle", path = "resources/bundle.html", source = "./docs/resources/13-bundle.md" },
  { title = "• JSON", path = "resources/json.html", source = "./docs/resources/14-json.md" },
  { title = " ", path = "#", source = "" },
  { title = "Gleam FHIR Clients", path = "clients.html", source = "./docs/clients/01-fhirclient.md" },
  { title = "• Client for httpc", path = "clients/httpc.html", source = "./docs/clients/02-httpc.md" },
  { title = "• Client for rsvp", path = "clients/rsvp.html", source = "./docs/clients/03-rsvp.md" },
  { title = "• sans-io", path = "clients/sansio.html", source = "./docs/clients/04-sansio.md" },
  { title = "• Handling Errors", path = "clients/handlingerrors.html", source = "./docs/clients/05-handlingerrors.md" },
  { title = "• CRUD", path = "clients/crud.html", source = "./docs/clients/06-crud.md" },
  { title = "• Search", path = "clients/search.html", source = "./docs/clients/07-search.md" },
  { title = "• Operations", path = "clients/operations.html", source = "./docs/clients/08-operations.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
json = ">= 1.4.1 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
