name = "fhir"
version = "0.0.0"

description = "Type-safe FHIR resources and client"
licences = ["MIT"]
repository = { type = "github", user = "PotatoEMR", repo = "https://github.com/PotatoEMR/gleam-fhir" }
# links = [{ title = "Website", href = "" }]

internal_modules = ["internal/*",]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
json = ">= 1.4.1 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
