name = "fhir"
version = "0.0.0"

description = "Type-safe FHIR resources and client"
licences = ["MIT"]
repository = { type = "github", user = "PotatoEMR", repo = "gleam-fhir" }

links = [
  { title = "Todo Issues", href = "https://github.com/PotatoEMR/gleam-fhir/issues/" },
]

[documentation]
pages = [
  { title = "Release Notes", path = "releasenotes.html", source = "./ReleaseNotes.md" },
  { title = " ", path = "#", source = "" },
  { title = "Gleam FHIR Resources", path = "resources.html", source = "./docs/resources/fhirresources.md" },
  { title = "• Primitive Type", path = "resources/primitivetype.html", source = "./docs/resources/primitivetype.md" },
  { title = "• Complex Type", path = "resources/complextype.html", source = "./docs/resources/complextype.md" },
  { title = "• BackboneElement", path = "resources/backboneelement.html", source = "./docs/resources/backboneelement.md" },
  { title = "• Cardinality", path = "resources/cardinality.html", source = "./docs/resources/cardinality.md" },
  { title = "• Choice Element", path = "resources/choiceelement.html", source = "./docs/resources/choiceelement.md" },
  { title = "• id vs Identifier", path = "resources/id-vs-identifier.html", source = "./docs/resources/idvsidentifier.md" },
  { title = "• Reference", path = "resources/reference.html", source = "./docs/resources/reference.md" },
  { title = "• code", path = "resources/code.html", source = "./docs/resources/code.md" },
  { title = "• Coding", path = "resources/coding.html", source = "./docs/resources/coding.md" },
  { title = "• CodeableConcept", path = "resources/codeableconcept.html", source = "./docs/resources/codeableconcept.md" },
  { title = "• CodeableReference", path = "resources/codeablereference.html", source = "./docs/resources/codeablereference.md" },
  { title = "• Extension", path = "resources/extension.html", source = "./docs/resources/extension.md" },
  { title = "• Bundle", path = "resources/bundle.html", source = "./docs/resources/bundle.md" },
  { title = "• JSON", path = "resources/json.html", source = "./docs/resources/json.md" },
  { title = " ", path = "#", source = "" },
  { title = "Gleam FHIR Clients", path = "clients.html", source = "./docs/clients/fhirclient.md" },
  { title = "• Client for httpc", path = "clients/httpc.html", source = "./docs/clients/httpc.md" },
  { title = "• Client for rsvp", path = "clients/rsvp.html", source = "./docs/clients/rsvp.md" },
  { title = "• sans-io", path = "clients/sansio.html", source = "./docs/clients/sansio.md" },
  { title = "• Handling Errors", path = "clients/handlingerrors.html", source = "./docs/clients/handlingerrors.md" },
  { title = "• CRUD", path = "clients/crud.html", source = "./docs/clients/crud.md" },
  { title = "• Search", path = "clients/search.html", source = "./docs/clients/search.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
json = ">= 1.4.1 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
